### ISSUE TITLE
npm run dist fails during webpack stage

### ISSUE THREAD

**Issue by haydnnewport** [springload/frontend-starter-kit#82] opened 2017-08-01 23:39 UTC
I've recently started a new project from Cookiecutter, with the most recent frontend-starter-kit version, and attempting to run `npm run dist` locally fails with the error below

```
haydn@c137:~/git/engineeringnz$ npm run dist

> frontend-starter-kit@1.0.0 dist /home/haydn/git/engineeringnz
> NODE_ENV=production gulp build

[11:36:22] Using gulpfile ~/git/engineeringnz/gulpfile.js
[11:36:22] Starting 'css'...
[11:36:22] Starting 'svg'...
[11:36:22] Starting 'js'...
[11:36:23] Finished 'css' after 165 ms
[11:36:23] Finished 'svg' after 153 ms
/home/haydn/git/engineeringnz/gulpfile.js/tasks/js.js:11
        const message = stats.toString(Object.assign({}, webpackConfig.stats, { timings: false }));
                             ^

TypeError: Cannot read property 'toString' of undefined
    at webpack.run (/home/haydn/git/engineeringnz/gulpfile.js/tasks/js.js:11:30)
    at /home/haydn/git/engineeringnz/node_modules/webpack/lib/Compiler.js:248:22
    at Compiler.<anonymous> (/home/haydn/git/engineeringnz/node_modules/webpack/lib/Compiler.js:350:19)
    at /home/haydn/git/engineeringnz/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/haydn/git/engineeringnz/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /home/haydn/git/engineeringnz/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at fs.js:1279:7
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend-starter-kit@1.0.0 dist: `NODE_ENV=production gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend-starter-kit@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/haydn/.npm/_logs/2017-08-01T23_36_23_133Z-debug.log

```

**Comment by thibaudcolas** [comment] 2017-08-04 20:20
Interesting! Looking at the exact code path here, Webpack is reporting errors in its `err` object and for some reason does not pass any value for `stats`. Could you `console.log(err);` before this line, and-or try the code change below:

```diff
gulp.task('js', (done) => {
    webpack(webpackConfig).run((err, stats) => {
        const hasErrors = err || stats.hasErrors();
-       const message = stats.toString(Object.assign({}, webpackConfig.stats, { timings: false }));

        if (hasErrors) {
            throw new gutil.PluginError('webpack', {
-                message: err ? err.details : message,
+                message: err ? err.details : 'failed',
            });
        } else {
+           const message = stats.toString(Object.assign({}, webpackConfig.stats, { timings: false }));
            console.log(message);

            done();
        }
    });
});
```

**Comment by haydnnewport** [comment] 2017-08-06 21:41
Ah, right - that's got it. Looks like there's a permissions issue (probably because of the docker frontend container)
```{ Error: EACCES: permission denied, open '/home/haydn/git/engineeringnz/core/static/js/site.js'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/haydn/git/engineeringnz/core/static/js/site.js' }
```

After applying the change above, I get
```/home/haydn/git/engineeringnz/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');```
as err.details is empty in the case above.

We might want to change or add to the `PluginError` message picking logic for the case where we have one of these system-level errors (assuming the other expected errors would still have a `details` attribute)

**Comment by thibaudcolas** [comment] 2017-08-09 20:45
Just added a fix for this in #84 (reproduced by doing a `chmod -rw core/static/js/site.js`). Here is what the error message now looks like:

```
[17:41:54] Using gulpfile ~/Dev/hacks/frontend-starter-kit/gulpfile.js
[17:41:54] Starting 'js'...
[17:41:57] 'js' errored after 3.5 s
[17:41:57] Error in plugin 'webpack'
Message:
    EACCES: permission denied, open '/Users/thibaud/Dev/hacks/frontend-starter-kit/core/static/js/site.js'
Details:
    errno: -13
    code: EACCES
    syscall: open
    path: /Users/thibaud/Dev/hacks/frontend-starter-kit/core/static/js/site.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend-starter-kit@1.0.0 js: `gulp js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend-starter-kit@1.0.0 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thibaud/.npm/_logs/2017-08-09T14_41_58_882Z-debug.log
```

I also changed how the error is raised so it follows the best practices of `gulp` and has the proper stack trace (or lack thereof).

**Comment by haydnnewport** [comment] 2017-08-09 21:43
Awesome, thanks Thibaud. Clearer error messages for everyone! :100:

**Closed** 2017-08-10 08:41 UTC
Labels: bug

**Comment by thibaudcolas** [comment] 2017-08-10 08:53
Merged! Let me know if I can help backporting this to your project @haydnnewport.
